from .aritmetica import *
from .algebra import *
from .lineal import *
from .trigonometria import *
from .calculo import *
from .geometria import *
from .estadistica import *
from .fisica import *
from .conversiones import *